### ISSUE TITLE
cycle counter

### ISSUE THREAD

**Issue by Onixarts** [robertsLando/node-red-contrib-scenario#1]
Hi. I found this node very usefull in my home automation, but I need few more things to make it perfect for my needs :). 

Node is loop forever. It would be great if there will be repetition counter to set up. In my case, I need to process all the scenes only ones. I've put in scenes natural language commands that my system recognizes so I can implement scenes/scenarios that for dims all my lights for example.

If project is still active do You consider adding this feature? Or maybe You will accept a pull requests?

**Comment by robertsLando** [comment]
I accept pr for sure! will be glad to review it , the code is really simple so it should be not that difficult to implement!

Daniel

**Comment by Onixarts** [comment]
I've created a #2

**Comment by robertsLando** [comment]
@Onixarts Version 1.1.0 is on npm now
